healthCheckTimeout: 900
logLevel: debug
logTimeFormat: rfc3339nano
logToStdout: proxy
metricsMaxInMemory: 1000

models:
  orpheus-3b: &model-base
    concurrencyLimit: 10
    proxy: "http://${MODEL_ID}:${PORT}"
    cmd: /bin/sh -c 'LLAMA_ARG_PORT=${PORT} docker compose up ${MODEL_ID}'
    cmdStop: docker compose stop ${MODEL_ID}
    ttl: 300

  qwen3.5-2b:
    <<: *model-base

  qwen3.5-35b:
    <<: *model-base

  whisper-large-v3:
    <<: *model-base
    checkEndpoint: /v1/audio/transcriptions/

groups:
  tiny:
    exclusive: false
    members:
      - qwen3.5-2b
    persistent: true
    swap: false
